baseURL = "https://awesome-light.garado.dev/"
languageCode = "en-us"
title = "awesome-light"
theme = "awesome-light"

enableRobotsTXT = true

[frontmatter]
  date = ["date_added", "date", ":default"]
  lastmod = [":git", "lastmod", "date", ":fileModTime"]

[params]
  description = "Community-developed apps and tools for the Light Phone."
  bg = "#464646"
  githubRepo = "https://github.com/garado/awesome-light"
  githubBranch = "main"

[markup.goldmark.renderer]
  unsafe = true

[imaging]
  resampleFilter = "Lanczos"

[security]
  [security.funcs]
    getenv = ["^GITHUB_TOKEN$"]
  [security.http]
    urls = ["^https://"]

[caches]
  [caches.getresource]
    maxAge = "6h"
